
#ifndef SMART_SCREEN_NOFARE_DEFINITIONS_H
#define SMART_SCREEN_NOFARE_DEFINITIONS_H

#define MESSAGE_QUEUE_NAME "nofare_message_queue"
#define MAX_MESSAGE_NUMBER 100
#define MAX_MESSAGE_SIZE 200

#endif //SMART_SCREEN_NOFARE_DEFINITIONS_H
